name: exlukdev-dotnetfw

on:
  workflow_dispatch: # Manual trigger only
  # push:
  #  branches:
  #    - main
  #  paths:
  #    - 'dotnetfw/**'

jobs:
  build:
    runs-on: [self-hosted, exlukdev] # Label from your runner setup

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet Packages
        run: nuget restore "dotnetfw/FTPGitTest.csproj"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # ➡️ ADD THIS STEP ⬅️
      - name: Create Publish Directory
        run: New-Item -ItemType Directory -Force -Path "D:\build\AllAppsBuild\dotnetfw"

      - name: Build and Publish
        run: |
          msbuild "FTPGitTest.csproj" `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:PublishProfile=FolderProfile `
            /p:PublishDir="D:\build\AllAppsBuild\dotnetfw\"
        working-directory: ./dotnetfw
